# encoding=utf-8


from gi.repository import GLib
import os


PROXY_URI = ''
API = 'pydict.youdao'


GROUP = 'main'
PROXY_KEY = 'http-proxy'
API_KEY = 'api'


KEYFILE_PATH = os.path.join(GLib.get_user_config_dir(), 'ydict.config')


def get_config_keyfile():
    """"""
    kf = GLib.KeyFile.new()
    global KEYFILE_PATH
    try:
        kf.load_from_file(KEYFILE_PATH, GLib.KeyFileFlags.NONE)
    except:
        pass
    return kf


def keyfile_get_string(kf, group, key, default):
    try:
        return kf.get_string(group, key)
    except:
        pass
    return default


def load_config():
    """读取配置"""
    global GROUP, PROXY_KEY, PROXY_URI, API
    kf = get_config_keyfile()
    PROXY_URI = keyfile_get_string(kf, GROUP, PROXY_KEY, PROXY_URI)
    API = keyfile_get_string(kf, GROUP, API_KEY, API)


def save_config():
    """保存配置"""
    global GROUP, PROXY_KEY, PROXY_URI, API
    kf = get_config_keyfile()
    kf.set_string(GROUP, PROXY_KEY, PROXY_URI)
    kf.set_comment(GROUP, PROXY_KEY, 'http proxy url')

    kf.set_string(GROUP, API_KEY, API)
    kf.set_comment(GROUP, API_KEY, 'the api service module name')

    kf.set_comment(GROUP, None, 'do not edit this file')
    kf.save_to_file(KEYFILE_PATH)
